#:schema node_modules/wrangler/config-schema.json
name = "zzalang-api"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[kv_namespaces]]
binding = "POSTS"
id = "db604d9231c74083ad177e0bffda3e7b"
preview_id = "475101c5054d4b978526ebfce19668ad"
